# WARNING - WARNING - WARNING - WARNING - WARNING
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
#$$$$$$$$$$$$$$$$Y/'$$$$P'a$$$$$$$$$$$$$$$$
#$$$$$$$$$",` /,/,mT$$$$ d$$$$$$$$$$$$$$$$$
#$$$$$l',` , '/d$$$$P^$a `^a`W$$$$$$$$$$$$$
#$$l', ` ,   |d$$$P^$'   _  _ ==~a$$$$$$$$$
#$l.`  .     \'i$^4'   _eP$$$$$$$$$$$$$$$$$
#l '  .         /   ,  $$$$' `$~$$$$$$$$$$$
#; ' ,              l /^' .,$oa$$$$$$$$$$$$
#b ' ,        .     (_ ,1$$$$$$'$$$$$$$$$$$
#$ , ,      .;       _$$$$$$$P $a$$$$$$$$$$
#$, ,`    .$Ly        lM"^ ,  ,$$$$$$$'$$$$
#$$, ,`   d$Liy      /'   edb $$$$$$$'$$$$$
#$$$$,,'. $$$Li     (    d$$$$$$$$$$'$$$$$$
#$$$$$$,' v$$$Li4.   `  `Q$$$$$$$P',$$$$$$$
#$$$$$$$$,$$$$$$$L44., . .     ,,;d$$$$$$$$
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#   Let it be known that HERE BE DRAGONS
# You should always be leaving these values
# blank. MC-MCVault-Config will by default read
# from the environment variables (you can even
# specify more options)! PLEASE PLEASE I beg of
# you. USE ENVIRONMENT VARIABLES!
# WARNING - WARNING - WARNING - WARNING - WARNING
address: ''
token: ''